name: CI

on:            # Cuándo se ejecuta
  push:        # cada vez que hagas git push
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest   # Servidor donde corre

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar tests
        run: pytest
